quarkus.datasource.jdbc.url=
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=update
quarkus.http.auth.form.enabled=true
quarkus.http.auth.session.encryption-key=
quarkus.http.auth.form.login-page=/auth/login
quarkus.http.auth.form.error-page=/error
quarkus.http.auth.form.landing-page=/dashboard/main
quarkus.http.limits.max-body-size=10M
# quarkus.http.static-dir.path=uploads/materials
# quarkus.http.static-dir.endpoint=/materials
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=
quarkus.s3.aws.credentials.static-provider.secret-access-key=
quarkus.s3.aws.region=eeur
quarkus.s3.path-style-access=true
quarkus.s3.endpoint-override=
public.url=
backet.name=
